
# special configuration for rules
line_length:
  warning: 150
  error: 200
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: false

disabled_rules:
- trailing_whitespace
- nesting

file_length:
  warning: 200
  error: 300

identifier_name:
  excluded:
    - i
    - j
    - k
    - q
    - id
    - no

function_parameter_count:
  warning: 5
  error: 8

function_body_length:
  warning: 25
  error: 30





















